"""add manual page structure

Revision ID: 1737f3bf6088
Revises: 5f681b132f73
Create Date: 2026-06-10 17:23:59.294641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1737f3bf6088'
down_revision: Union[str, Sequence[str], None] = '5f681b132f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_page_structures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.Enum('cover', 'parts_inventory', 'assembly_step', 'mixed_inventory_and_step', 'informational', 'back_matter', 'unknown', name='manual_page_type'), nullable=False),
    sa.Column('visible_step_numbers', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_page_structures_document_id'), 'manual_page_structures', ['document_id'], unique=False)
    op.create_index(op.f('ix_manual_page_structures_page_number'), 'manual_page_structures', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_page_structures_page_number'), table_name='manual_page_structures')
    op.drop_index(op.f('ix_manual_page_structures_document_id'), table_name='manual_page_structures')
    op.drop_table('manual_page_structures')
    # ### end Alembic commands ###
