"""add phase 3 steps tasks and review events

Revision ID: 57f034009c85
Revises: ec6a5e659303
Create Date: 2026-06-06 19:46:00.740663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f034009c85'
down_revision: Union[str, Sequence[str], None] = 'ec6a5e659303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('gate_number', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('fields_edited', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_gate_number'), 'review_events', ['gate_number'], unique=False)
    op.create_index(op.f('ix_review_events_job_id'), 'review_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_review_events_reviewer_id'), 'review_events', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_events_target_id'), 'review_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_review_events_tenant_id'), 'review_events', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.String(length=128), nullable=True),
    sa.Column('orientation', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_document_id'), 'steps', ['document_id'], unique=False)
    op.create_index(op.f('ix_steps_job_id'), 'steps', ['job_id'], unique=False)
    op.create_index(op.f('ix_steps_order_index'), 'steps', ['order_index'], unique=False)
    op.create_index(op.f('ix_steps_step_number'), 'steps', ['step_number'], unique=False)
    op.create_index(op.f('ix_steps_task_id'), 'steps', ['task_id'], unique=False)
    op.create_index(op.f('ix_steps_tenant_id'), 'steps', ['tenant_id'], unique=False)
    op.create_table('step_source_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_source_evidence_source_evidence_id'), 'step_source_evidence', ['source_evidence_id'], unique=False)
    op.create_index(op.f('ix_step_source_evidence_step_id'), 'step_source_evidence', ['step_id'], unique=False)
    op.create_index(op.f('ix_step_source_evidence_tenant_id'), 'step_source_evidence', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_source_evidence_tenant_id'), table_name='step_source_evidence')
    op.drop_index(op.f('ix_step_source_evidence_step_id'), table_name='step_source_evidence')
    op.drop_index(op.f('ix_step_source_evidence_source_evidence_id'), table_name='step_source_evidence')
    op.drop_table('step_source_evidence')
    op.drop_index(op.f('ix_steps_tenant_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_task_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_step_number'), table_name='steps')
    op.drop_index(op.f('ix_steps_order_index'), table_name='steps')
    op.drop_index(op.f('ix_steps_job_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_document_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_review_events_tenant_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_target_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_reviewer_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_job_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_gate_number'), table_name='review_events')
    op.drop_table('review_events')
    # ### end Alembic commands ###
