"""create full beacon schema

Revision ID: 5f681b132f73
Revises: 
Create Date: 2026-06-07 21:25:27.297432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f681b132f73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('scanned_flag', sa.Boolean(), nullable=False),
    sa.Column('detected_language', sa.String(length=32), nullable=True),
    sa.Column('suitability_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('page_image_key', sa.String(length=1024), nullable=True),
    sa.Column('text_extraction_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_page_number'), 'document_pages', ['page_number'], unique=False)
    op.create_index(op.f('ix_document_pages_tenant_id'), 'document_pages', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'INGESTING', 'EXTRACTING_EVIDENCE', 'EXTRACTING_STEPS', 'AWAITING_REVIEW_1', 'STORYBOARDING', 'AWAITING_REVIEW_2', 'DETERMINISTIC_RENDERING', 'OPTIONAL_GENERATING', 'COMPOSING', 'AWAITING_REVIEW_3', 'EXPORTING', 'COMPLETED', 'NEEDS_ATTENTION', 'FAILED', name='jobstate'), nullable=False),
    sa.Column('cost_estimate_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_document_id'), 'jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_job_id'), 'audit_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('review_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('gate_number', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('fields_edited', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_events_gate_number'), 'review_events', ['gate_number'], unique=False)
    op.create_index(op.f('ix_review_events_job_id'), 'review_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_review_events_reviewer_id'), 'review_events', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_review_events_target_id'), 'review_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_review_events_tenant_id'), 'review_events', ['tenant_id'], unique=False)
    op.create_table('source_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_page_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text_start', sa.Integer(), nullable=True),
    sa.Column('text_end', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('x', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('y', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coordinate_system', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validation_flag', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_evidence_document_id'), 'source_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_source_evidence_document_page_id'), 'source_evidence', ['document_page_id'], unique=False)
    op.create_index(op.f('ix_source_evidence_evidence_type'), 'source_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_source_evidence_page_number'), 'source_evidence', ['page_number'], unique=False)
    op.create_index(op.f('ix_source_evidence_tenant_id'), 'source_evidence', ['tenant_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_document_id'), 'tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.String(length=128), nullable=True),
    sa.Column('orientation', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('source_page_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_document_id'), 'steps', ['document_id'], unique=False)
    op.create_index(op.f('ix_steps_job_id'), 'steps', ['job_id'], unique=False)
    op.create_index(op.f('ix_steps_order_index'), 'steps', ['order_index'], unique=False)
    op.create_index(op.f('ix_steps_step_number'), 'steps', ['step_number'], unique=False)
    op.create_index(op.f('ix_steps_task_id'), 'steps', ['task_id'], unique=False)
    op.create_index(op.f('ix_steps_tenant_id'), 'steps', ['tenant_id'], unique=False)
    op.create_table('step_source_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('source_evidence_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['source_evidence.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_source_evidence_source_evidence_id'), 'step_source_evidence', ['source_evidence_id'], unique=False)
    op.create_index(op.f('ix_step_source_evidence_step_id'), 'step_source_evidence', ['step_id'], unique=False)
    op.create_index(op.f('ix_step_source_evidence_tenant_id'), 'step_source_evidence', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_source_evidence_tenant_id'), table_name='step_source_evidence')
    op.drop_index(op.f('ix_step_source_evidence_step_id'), table_name='step_source_evidence')
    op.drop_index(op.f('ix_step_source_evidence_source_evidence_id'), table_name='step_source_evidence')
    op.drop_table('step_source_evidence')
    op.drop_index(op.f('ix_steps_tenant_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_task_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_step_number'), table_name='steps')
    op.drop_index(op.f('ix_steps_order_index'), table_name='steps')
    op.drop_index(op.f('ix_steps_job_id'), table_name='steps')
    op.drop_index(op.f('ix_steps_document_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_document_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_source_evidence_tenant_id'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_page_number'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_evidence_type'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_document_page_id'), table_name='source_evidence')
    op.drop_index(op.f('ix_source_evidence_document_id'), table_name='source_evidence')
    op.drop_table('source_evidence')
    op.drop_index(op.f('ix_review_events_tenant_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_target_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_reviewer_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_job_id'), table_name='review_events')
    op.drop_index(op.f('ix_review_events_gate_number'), table_name='review_events')
    op.drop_table('review_events')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_job_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_document_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_document_pages_tenant_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_page_number'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
